services:
  front:
    container_name: front
    image: was24/front
    build:
      context: ./firstserver
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    

  back:
    container_name: back
    image: was24/back
    build:
      context: ./secondserver
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    