#Setting up service for the deployment back of type LoadBalancer to expose it to external traffic
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  type: LoadBalancer 
  selector:
    app: back
  ports:
  - port: 4000
    targetPort: 4000

---

#Creating the actual deployment for back
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: was24/back
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 4000
