services:
  front:
    container_name: front
    image: ${account}/front:${version}
    build:
      context: ./firstserver
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    

  back:
    container_name: back
    image: ${account}/back:${version}
    build:
      context: ./secondserver
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - front
    