apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
#Creating Front Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ${account}/front
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000

---

#Creating service named as "front" for our deployment
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: devops
spec:
  selector:
    app: front
  ports:
  - port: 3000
    targetPort: 3000

---

#Setting up horizontal Pod Autoscaler, which will autoscale our deployment based on the load of the application
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-hpa
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50