#Creating service named as "back" for our deployment of type LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: back
  namespace: devops
spec:
  type: LoadBalancer 
  selector:
    app: back
  ports:
  - port: 4000
    targetPort: 4000



---
#Creating deplopyment back with 3 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ${account}/back
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 4000

---

#Setting up hpa for back deployment
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: back-hpa
  namespace: devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
