apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  type: LoadBalancer 
  selector:
    app: back
  ports:
  - port: 4000
    targetPort: 4000



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ${account}/back
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 4000
